version: '3.9'
services:
  deepfake:
    build:
      context: ../.docker
      dockerfile: Dockerfile
    image: skrjtech/myfaceswap:pycharm
    container_name: myfaceswap_container
    hostname: myfaceswap
    tty: true
    restart: always
    environment:
      - DISPLAY=$DISPLAY
    # devices:
    #   - /dev/video0:/dev/video0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ..:/ws
      - ../..:/Output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - 8888:8888