version: '3.9'
services:
  astvs:
    # build:
    #   context: ../.docker
    #   dockerfile: Dockerfile
    #   args:
    #     - IMAGETAG=skrjtech/python:debian-python3.9.16
    image: skrjtech/astvs:debian-python3.9.16
    container_name: astvs_container
    hostname: astvs
    tty: true
    restart: always
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
    # devices:
    #   - /dev/video0:/dev/video0
    #   - /dev/snd:/dev/snd
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ..:/ws
      - ../DATABASE:/DATABASE
      - pycharm_volume:/tmp/pycharm
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  pycharm:
    image: skrjtech/pycharm:debian
    container_name: pycharm_container
    tty: true
    restart: always
    volumes:
      - type: volume
        source: pycharm_volume
        target: /tmp/pycharm
    depends_on:
      - astvs

volumes:
  pycharm_volume: