version: '3.9'
services:
  deepfake:
    build:
      context: ../.docker
      dockerfile: Dockerfile
    image: skrjtech/mydeepfake:latest
    container_name: mydeepfake_container
    hostname: deepfake
    tty: true
    restart: always
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ..:/ws
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - 8888:8888
      