version: '3.9'
services:
  astvs:
    # build:
    #   context: ../.docker
    #   dockerfile: Dockerfile
    image: skrjtech/astvs
    container_name: astvs
    hostname: astvs
    tty: true
    restart: always
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video10:/dev/video10
      - /dev/snd:/dev/snd
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ..:/ASTVSHome

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]